### ISSUE TITLE
Insert timestamp() problem.

### ISSUE THREAD

**Issue by zeucxb** [ankhers/mongodb_ecto#146]
I'm with this error in my tests

```
1) test users list_users/0 returns all users (NeopagApiStore.AccountTest)
     test/neopag_api_store/account/account_test.exs:22
     Assertion with == failed
     code:  assert Account.list_users() == [user]
     left:  [%NeopagApiStore.Account.User{__meta__: #Ecto.Schema.Metadata<:loaded, "users">, active: true, cpf: "some cpf", email: "some email", id: "5a217a7735dbc00cd7aeb96e", name: "some name", password: nil, password_hash: nil, phone: "some phone", inserted_at: %NaiveDateTime{calendar: Calendar.ISO, day: 1, hour: 15, minute: 51, month: 12, second: 19, year: 2017, microsecond: {33000, 6}}, updated_at: %NaiveDateTime{calendar: Calendar.ISO, day: 1, hour: 15, minute: 51, month: 12, second: 19, year: 2017, microsecond: {42000, 6}}}]
     right: [%NeopagApiStore.Account.User{__meta__: #Ecto.Schema.Metadata<:loaded, "users">, active: true, cpf: "some cpf", email: "some email", id: "5a217a7735dbc00cd7aeb96e", name: "some name", password: nil, password_hash: nil, phone: "some phone", inserted_at: %NaiveDateTime{calendar: Calendar.ISO, day: 1, hour: 15, minute: 51, month: 12, second: 19, year: 2017, microsecond: {33525, 6}}, updated_at: %NaiveDateTime{calendar: Calendar.ISO, day: 1, hour: 15, minute: 51, month: 12, second: 19, year: 2017, microsecond: {42219, 6}}}]
     stacktrace:
       test/neopag_api_store/account/account_test.exs:24: (test)
```

**Basically, the user returned from my `create_user` function has a different timestamp when compared with the database one, returned from `get_user`.**

``` elixir
def create_user(attrs \\ %{}) do
  %User{}
  |> User.changeset(attrs)
  |> Repo.insert()
end

def get_user!(id), do: Repo.get!(User, id)

def user_fixture(attrs \\ %{}) do
  {:ok, user} =
    attrs
    |> Enum.into(@valid_attrs)
    |> Account.create_user()

  user
end

test "get_user!/1 returns the user with given id" do
    user = user_fixture()
    assert Account.get_user!(user.id) == user
end
```

**Comment by ankhers** [comment]
Can you please provide the version of the adapter that you are using?

**Comment by zeucxb** [comment]
@ankhers ecto-2.1

**Comment by ankhers** [comment]
(https://github.com/ankhers/mongodb_ecto/blob/ecto-2.1/lib/mongo_ecto.ex#L503-L510) or [load](https://github.com/ankhers/mongodb_ecto/blob/ecto-2.1/lib/mongo_ecto.ex#L446-L451) the data from the database. 

Thanks for reporting this. I will look into it when I have a bit more time.

**Comment by habutre** [comment]
Hey guys I took some time to try understand this issue and I had some assumptions which I would like to share with you:

1. Mongo DB uses time with _millis_ instead _microseconds_
1. The values returned from `insert/2` seems to be the `NaiveDateTime` used to persist on mongo DB
1. The values returned from `get!/3` are the _millis_ from `mongo` to _micros_ on `ecto`

@zeucxb if you don't mind about these microseconds on `timestamps()` its possible to disable using [timestamps(usec: false)](https://hexdocs.pm/ecto/Ecto.Schema.html#timestamps/1) so your tests will not fail due that difference, otherwise you have compare field by field on `%User{}` skipping `inserted_at` and `updated_at`
